# Generated by Django 3.0.5 on 2020-04-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200424_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='follow_up',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
