# Generated by Django 3.0.5 on 2020-04-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_follow_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expires',
            field=models.DateField(blank=True, null=True),
        ),
    ]
