# Generated by Django 3.0.5 on 2020-04-23 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200424_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='electric_power',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.ElectricPower'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='foor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.FoorType'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='storey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Storey'),
        ),
    ]
