# Generated by Django 3.0.5 on 2020-04-23 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200424_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='notes',
            new_name='customer_notes',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
