# Generated by Django 3.0.5 on 2020-04-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20200425_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='deposit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='extra_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='installation_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='last_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
