# Generated by Django 3.0.5 on 2020-04-25 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_customer_customer_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='installer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Installer'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='installer_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='installer_date_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Requirement')),
            ],
        ),
    ]
