# Generated by Django 3.0.5 on 2020-04-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20200425_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='date_paid',
            new_name='supplier_date_paid',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='invoice',
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_invoice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
