# Generated by Django 3.0.5 on 2020-04-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20200426_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='order_paid',
            field=models.BooleanField(default=False),
        ),
    ]
