# Generated by Django 3.0.5 on 2020-04-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20200426_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='stc_paid',
            field=models.BooleanField(default=False),
        ),
    ]
