# Generated by Django 3.0.5 on 2020-04-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_requirement_stc_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
    ]
