# Generated by Django 3.0.5 on 2020-04-27 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20200427_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='credit_card',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')]),
        ),
    ]
