# Generated by Django 3.0.5 on 2020-04-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_auto_20200428_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='kw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
