# Generated by Django 3.0.5 on 2020-04-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_auto_20200428_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
