# Generated by Django 3.0.5 on 2020-04-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_supplier_supplier_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='meter_connection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='power_connection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
