# Generated by Django 3.0.5 on 2020-04-29 04:49

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('customer', '0031_auto_20200429_1252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoorType',
            new_name='RoofType',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='foor_type',
            new_name='roof_type',
        ),
    ]
