# Generated by Django 3.0.5 on 2020-04-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_remove_requirement_deposit_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='deposit',
            new_name='deposit_amount',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='deposit_date',
            new_name='deposit_date_paid',
        ),
    ]
