# Generated by Django 3.0.5 on 2020-04-29 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_auto_20200430_0732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='stc',
            new_name='stc_amount',
        ),
    ]
