# Generated by Django 3.0.5 on 2020-04-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_auto_20200430_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='service_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
