# Generated by Django 3.0.5 on 2020-04-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_requirement_service_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='stc_paid',
        ),
        migrations.AddField(
            model_name='requirement',
            name='stc_date_paid',
            field=models.DateField(blank=True, null=True),
        ),
    ]
