# Generated by Django 3.0.5 on 2020-04-30 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0040_auto_20200430_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='leads_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Lead'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_salesman', to=settings.AUTH_USER_MODEL),
        ),
    ]
