# Generated by Django 3.0.5 on 2020-04-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_remove_requirement_service_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(default='CREATED', max_length=50),
        ),
    ]
