# Generated by Django 3.0.5 on 2020-05-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_auto_20200501_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlookTokenCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('subscription_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('subscription_alive', models.BooleanField(blank=True, default=False)),
                ('token_cache', models.TextField(blank=True, max_length=10000, null=True)),
                ('token_alive', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
