# Generated by Django 3.0.5 on 2020-05-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_outlooktokencache'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutlookTokenCache',
        ),
    ]
