# Generated by Django 2.1.7 on 2020-05-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_delete_outlooktokencache'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='finance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='system_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
