# Generated by Django 2.1.7 on 2020-05-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0048_auto_20200522_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='balance_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='stc_amount_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='stc_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
