# Generated by Django 2.1.7 on 2020-05-21 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0049_auto_20200522_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='notes',
            new_name='stc_notes',
        ),
    ]
