# Generated by Django 2.1.7 on 2020-05-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_auto_20200522_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='STC_PAYMENT',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
