# Generated by Django 2.1.7 on 2020-05-21 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_requirement_stc_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='last_amount_balance_due',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='last_amount_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='last_amount_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='last_amount_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_last_amount_payment', to='customer.Payment'),
        ),
    ]
