# Generated by Django 2.1.7 on 2020-05-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_auto_20200522_0939'),
        ('customer', '0048_remove_customer_create_notification'),
    ]

    operations = [
    ]
