# Generated by Django 2.1.7 on 2020-05-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0053_merge_20200525_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='Installer_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
