# Generated by Django 2.1.7 on 2020-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0054_requirement_installer_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='STC_PAYMENT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='deposit_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='extra_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='installer_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='last_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='last_amount_balance_due',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='last_amount_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='stc_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='stc_amount_payment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='system_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='unit_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
