# Generated by Django 2.1.7 on 2020-05-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0055_auto_20200525_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
