# Generated by Django 3.0.5 on 2020-05-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlookserverdetails',
            options={'permissions': [('mailserver_view', 'Can view the mailserver details page')]},
        ),
    ]
